apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-spring-boot-app-k8s-v3
  title: sample-spring-boot-app-k8s-v3
  annotations:
    circleci.com/project-slug: github/banu-mphasis/sample-spring-boot-app-k8s-v3
    github.com/project-slug: banu-mphasis/sample-spring-boot-app-k8s-v3
    sonarqube.org/project-key: banu-mphasis_sample-spring-boot-app-k8s-v3
    backstage.io/kubernetes-label-selector: 'app=sample-spring-boot-app-k8s-v3'
    argocd/app-name: sample-spring-boot-app-k8s-v3
    prometheus.io/rule: container_memory_usage_bytes{pod=~"sample-spring-boot-app-k8s-v3-.*"}|pod,rate(container_cpu_usage_seconds_total{pod=~"sample-spring-boot-app-k8s-v3-.*"}[5m])|pod
  tags:
    - spring-boot
    - java
    - maven
    - circleci
    - renovate
    - sonarqube
spec:
  type: service
  owner: piotr.minkowski@gmail.com
  lifecycle: experimental
